// Generated by Selenium IDE
import es.uma.informatica.sii.anotaciones.Requisitos;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
@Requisitos({"RF10"})
public class RF10TestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rF10() {
    driver.get("http://localhost:8080/turingFintech-war/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.id("Acceso:user")).click();
    driver.findElement(By.id("Acceso:user")).sendKeys("ana");
    driver.findElement(By.id("Acceso:pass")).click();
    driver.findElement(By.id("Acceso:pass")).sendKeys("ana");
    driver.findElement(By.id("Acceso:pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".titulo")).click();
    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("Bienvenido a Ebury"));
    driver.findElement(By.linkText("Cuentas")).click();
    driver.findElement(By.cssSelector(".titulo")).click();
    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("Tus cuentas"));
  }
}
