// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RF5TestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rF5() {
    driver.get("http://localhost:8080/turingFintech-war/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.linkText("página de acceso")).click();
    driver.findElement(By.id("AccesoAdministrativos:user")).click();
    driver.findElement(By.id("AccesoAdministrativos:user")).sendKeys("ponciano");
    driver.findElement(By.id("AccesoAdministrativos:pass")).sendKeys("ponciano");
    driver.findElement(By.id("AccesoAdministrativos:pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Cuentas")).click();
    driver.findElement(By.id("cuentas:botonInsertarSegregada")).click();
    driver.findElement(By.id("cuentas:DNI")).click();
    driver.findElement(By.id("cuentas:DNI")).sendKeys("P3310693A");
    driver.findElement(By.id("cuentas:IBAN")).click();
    driver.findElement(By.id("cuentas:IBAN")).sendKeys("rf5");
    driver.findElement(By.id("cuentas:SWIFT")).click();
    driver.findElement(By.id("cuentas:SWIFT")).sendKeys("5");
    driver.findElement(By.id("cuentas:Cr")).click();
    driver.findElement(By.id("cuentas:Cr")).sendKeys("rf5es");
    driver.findElement(By.id("cuentas:Crswif")).click();
    driver.findElement(By.id("cuentas:Crswif")).sendKeys("es");
    driver.findElement(By.id("cuentas:CrNombre")).click();
    driver.findElement(By.id("cuentas:CrNombre")).sendKeys("rf5");
    driver.findElement(By.cssSelector("tr:nth-child(7) > td:nth-child(2)")).click();
    driver.findElement(By.id("cuentas:CrSurcursal")).click();
    driver.findElement(By.id("cuentas:CrSurcursal")).sendKeys("rf5");
    driver.findElement(By.id("cuentas:CrSurcursal")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("cuentas:CrSurcursal")).sendKeys(Keys.TAB);
    driver.findElement(By.id("cuentas:CrPais")).sendKeys("es");
    driver.findElement(By.id("cuentas:CrSaldo")).sendKeys("100");
    driver.findElement(By.id("cuentas:CrDiv")).sendKeys("EUR");
    driver.findElement(By.name("cuentas:j_idt27")).click();
    driver.findElement(By.id("cuentas:j_idt6:4:ide")).click();
    driver.findElement(By.id("cuentas:j_idt6:4:ide")).click();
    {
      WebElement element = driver.findElement(By.id("cuentas:j_idt6:4:ide"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.id("cuentas:j_idt6:4:ide")).getText(), is("rf5"));
    driver.findElement(By.id("cuentas:j_idt6:4:textoTipo")).click();
    driver.findElement(By.id("cuentas:j_idt6:4:textoTipo")).click();
    {
      WebElement element = driver.findElement(By.id("cuentas:j_idt6:4:textoTipo"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.id("cuentas:j_idt6:4:textoTipo")).getText(), is("Segregada"));
  }
}
